/*
* generated by Xtext
*/
package com.minimalabs.fiber.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FiberOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
