/*
 * generated by Xtext
 */
package com.minimalabs.fiber.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FiberExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.minimalabs.fiber.ui.internal.FiberActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.minimalabs.fiber.ui.internal.FiberActivator.getInstance().getInjector("com.minimalabs.fiber.Fiber");
	}
	
}
