/*
 * generated by Xtext
 */
package com.minimalabs.fiber.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FiberUiModule extends com.minimalabs.fiber.ui.AbstractFiberUiModule {
	public FiberUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
