/*
* generated by Xtext
*/
package com.minimalabs.fiber.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FiberAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/minimalabs/fiber/parser/antlr/internal/InternalFiber.tokens");
	}
}
