/*
 * generated by Xtext
 */
package com.minimalabs.fiber;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FiberRuntimeModule extends com.minimalabs.fiber.AbstractFiberRuntimeModule {

}
