/*
* generated by Xtext
*/
package com.minimalabs.fiber.ui.contentassist;

import com.minimalabs.fiber.ui.contentassist.AbstractFiberProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FiberProposalProvider extends AbstractFiberProposalProvider {

}
